name: Telegram Alert
description: A GitHub Action for sending build status alerts to a Telegram chat.
inputs:
  success-prefix:
    description: The prefix to use in a success alert, defaults to 😎.
    required: false
  failure-prefix:
    description: The prefix to use in a failure alert, defaults to 😱.
    required: false
  cancelled-prefix:
    description: The prefix to use in a cancelled alert, defaults to 🫥.
    required: false
  bot-token:
    description: The Telegram bot token for sending messages.
    required: true
  chat-id:
    description: The Telegram chat ID to send messages to.
    required: true
  success:
    description: Specifies whether this is a success or failure alert.
    required: true
  cancelled:
    description: Specifies whether this is a cancelled alert.
    required: false
  action-label:
    description: Label of the action button. If provided along with `action-url`, the action button will be visible if `success` is `true`.
    required: false
  action-url:
    description: Link of the action button. If provided along with `action-label`, the action button will be visible if `success` is `true`.
    required: false
outputs:
  response:
    description: The data of the Telegram API request.
runs:
  using: node20
  main: dist/index.js
